// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzrzyjiezjoeynoitqur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6cnp5amllempvZXlub2l0cXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTU2NjIsImV4cCI6MjA2ODE5MTY2Mn0.uBJfgtWou7sbi_sfoptp8xmtkJpDRe6YHSFO6ctduHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});